name: e2e

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  e2e:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 20
      BASE_URL: http://localhost:5173  # будет использовано тестами

    steps:
      - name: Checkout tests repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      # --- подтягиваем фронт ---
      - name: Checkout vue-crm (frontend)
        uses: actions/checkout@v4
        with:
          repository: harryho/vue-crm
          path: frontend
      - name: update problem dependency
        working-directory: frontend
        run: |
             # правим package.json в рабочей копии
              npm pkg set "dependencies.vite-plugin-vuetify"="2.1.2"
              # на всякий — убираем несовместимый webpack-плагин, если он есть
              npm pkg delete "dependencies.webpack-plugin-vuetify" || true
              npm pkg delete "devDependencies.sass-loader" || true
              # пересобираем локфайл под обновлённые зависимости
              rm -f package-lock.json
              npm install --no-audit --fund=false
      - name: Install & build frontend
        working-directory: frontend
        run: |
          npm install --no-audit --fund=false
          npm run build
          # стартуем предпросмотр Vite на 5173 (по умолчанию)
          npm run preview -- --host --port 5173 &

      # ждём пока сервер поднимется
      - name: Wait for frontend
        run: npx --yes wait-on ${{ env.BASE_URL }}

      # --- ставим playwright и браузеры ---
      - name: Install test deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          BASE_URL: ${{ env.BASE_URL }}

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7


#name: Playwright Tests
#on:
#  push:
#    branches: [ main, master ]
#  pull_request:
#    branches: [ main, master ]
#jobs:
#  test:
#    timeout-minutes: 60
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v4
#    - uses: actions/setup-node@v4
#      with:
#        node-version: lts/*
#    - name: Install dependencies
#      run: npm ci
#    - name: Install Playwright Browsers
#      run: npx playwright install --with-deps
#    - name: Run Playwright tests
#      run: npx playwright test
#    - uses: actions/upload-artifact@v4
#      if: ${{ !cancelled() }}
#      with:
#        name: playwright-report
#        path: playwright-report/
#        retention-days: 30
